services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv

  #  db:
  #    image: postgres:17.2
  #    restart: always
  #    # set shared memory limit when using docker-compose
  #    shm_size: 128mb
  #    # or set shared memory limit when deploy via swarm stack
  #    #volumes:
  #    #  - type: tmpfs
  #    #    target: /dev/shm
  #    #    tmpfs:
  #    #      size: 134217728 # 128*2^20 bytes = 128Mb
  #    ports:
  #      - '5432:5432'
  #    environment:
  #      POSTGRES_PASSWORD: password
  #      POSTGRES_USER: postgres
  #      POSTGRES_DB: biomed

  redis:
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    depends_on:
      - web

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    depends_on:
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

    depends_on:
      - promtail
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  grafanadata:
  prometheusdata: